### ISSUE TITLE
Two Repositories for MSP430 MCUs

### ISSUE THREAD

**Issue by rei-vilo** [energia/msp430-lg-core#1]
There are two repositories for the MSP430 MCU family.

* [msp430-lg-core](https://github.com/energia/msp430-lg-core), and
* [msp430-ng-core](https://github.com/energia/msp430-ng-core)

What `lg` and `ng` stand for?

_Also posted at [energia/msp430-ng-core](https://github.com/energia/msp430-ng-core/issues/1)._

**Comment by robertinant** [comment]
msp430-lg-core is the legacy core for msp430-gcc. msp430-ng-core is the next generation core for msp430-elf-gcc. In a couple months I will offer a second msp430 core based on msp430-elf-gcc. This way users can choose to stick with msp430-gcc or move on to msp430-elf-gcc or keep both.
