### ISSUE TITLE
GCC 4.6.6 compiler package: msp430.h file misses FR2155

### ISSUE THREAD

**Issue by LambertusIJsselstein** [energia/msp430-lg-core#124]
in the GCC compiler package 4.6.6
in msp430.h file the following lines are missing

#elif defined (MSP430FR2155)
#include "msp430fr2155.h"

Refs #77

**Comment by StefanSch** [comment]
Adding new devices to the Compiler used in Energia is quite an effort. Therefore just devices used on Launchpads are added just now.
