### ISSUE TITLE
MSP430F5529 : undefined reference to `operator new[](unsigned int)'

### ISSUE THREAD

**Issue by rei-vilo** [energia/msp430-lg-core#15]
Using `new` against the MSP430F5529 raises an error.

```
undefined reference to `operator new[](unsigned int)'
```

Maybe [energia/msp430-ng-core](https://github.com/energia/msp430-ng-core) will support it?

_Cross posted with https://github.com/energia/msp430-ng-core/issues/2_

**Comment by robertinant** [comment]
Can you please provide an example Sketch that shows the error?

**Comment by rei-vilo** [comment]
```
uint8_t * pointer;


void setup() {
  // put your setup code here, to run once:
  Serial.begin(9600);

  uint8_t * table = new uint8_t[16];
  pointer = (uint8_t *) table;

  pointer [1] = 1;
}

void loop() {
  // put your main code here, to run repeatedly:
  Serial.print(pointer[1], DEC);
  while (1);
}
```

**Comment by robertinant** [comment]
mspgcc does not have full support for C++. For example, there is no libstdc++. The new compiler soon to be featured in Energia will have more extensive support for C++.

**Comment by rei-vilo** [comment]
For the moment, the only turn-around is to define the arrays directly as variable without using `new()`.

**Comment by rei-vilo** [comment]
@robertinant Any update on the switch to the new compiler?

**Comment by RickKimball** [comment]
fixed with: https://github.com/energia/msp430-lg-core/commit/9b6fc95750b87eed164907902bfa23be29c01576
