### ISSUE TITLE
CCS 6.2 / Energia 18 libmsp430.so Release Conflict 

### ISSUE THREAD

**Issue by rei-vilo** [energia/msp430-lg-core#24]
There is a release conflict for the `libmsp430.so` file (also known as `libmsp430.dylib`) between CCS 6.2 and Energia 18.

**Comment by RickKimball** [comment]
An even better would be use the libmsp430.so that is in CCS 7.0. That code provides a 64bit executable so the 32 bit compatibility libraries aren't required.

**Comment by rei-vilo** [comment]
CCS has been updated to 7.1.
