### ISSUE TITLE
FR5994 — SD Detect P7_2 Not Listed

### ISSUE THREAD

**Issue by rei-vilo** [energia/msp430-lg-core#30]
The [SLAU678a](http://www.ti.com/lit/ug/slau678a/slau678a.pdf) mentions `SD Detect` connected to `P7_2`. 

However, it isn't listed in file [MSP-EXP430FR5994LP/pins_energia.h](https://github.com/energia/msp430-lg-core/blob/FR5994_FR2311_support/variants/MSP-EXP430FR5994LP/pins_energia.h). 

`SD Detect` is a very useful signal. Shouldn't be included?

**Comment by StefanSch** [comment]
added the pin to the pin map
