### ISSUE TITLE
Add FRAM attribute to Energia

### ISSUE THREAD

**Issue by rei-vilo** [energia/msp430-lg-core#31]
FRAM is an exclusive technology, but how to leverage it for large arrays?

Please document how to use FRAM as RAM with Energia.

**Comment by spirilis** [comment]
I had a thread on 43oh for Wolverine FRAM tips & tricks that might still apply...

**Comment by rei-vilo** [comment]
@spirilis Thank you for the pointer.

I've already saw and used the [trick](http://forum.43oh.com/topic/5474-energia-and-wolverine-tips/?p=47861) but I want it included and fully supported in Energia.

```
#define PERSIST __attribute__((section(".text")))
uint8_t DisplayBuffer[LCD_MAXIMUM_Y][LCD_MAXIMUM_X] PERSIST;
```

**Comment by spirilis** [comment]
Gotcha... Guess that would just mean Energia including the #define in its Energia.h file?

**Comment by rei-vilo** [comment]
Yes, plus some doc!

**Comment by rei-vilo** [comment]
Add `FRAM` attribute to Energia in the `pins_energia.h` related to FRAM-based LaunchPads.

```
#define FRAM __attribute__((section(".text")))
```

**Comment by rei-vilo** [comment]
See pull-request #32

**Comment by StefanSch** [comment]
I am a little bit burned child with short names esp. in defines and that they got reused.
May we can find a better / unique name, e.g.
STORE_IN_FRAM
PLACE_IN_FRAM
ALLOCATE_IN_FRAM
IN_FRAM
...

**Comment by rei-vilo** [comment]
`PLACE_IN_FRAM`seems fine, unless @robertinant has a better suggestion.

**Comment by rei-vilo** [comment]
See https://github.com/energia/msp430-lg-core/pull/32#issuecomment-275451946

**Comment by rei-vilo** [comment]
The FRAM is write protected on the MSP430FR2433. See #47.
