### ISSUE TITLE
Supply board manager JSON files

### ISSUE THREAD

**Issue by barawn** [energia/msp430-lg-core#36]
It would be good if the MSP430 package indexes were available for the boards that get pre-installed in Energia, so that we can have a working example to start from. I've been totally unable to make a custom board install via the Board Manager since I'm pretty much workinng blind.

**Comment by rei-vilo** [comment]
I'm not sure to understand your question. The list of the pre-installed MSP430 boards is available in 4 different locations:

* Boards Manager window under menu **Tools > Board > Boards Manager** 

<img width="800" alt="capture 2017-02-28 a 18 12 34" src="https://cloud.githubusercontent.com/assets/951776/23416159/0d93bfd6-fde2-11e6-9d97-4abd5524e21c.png">

* Boards list under menu **Tools > Board**

<img width="856" alt="capture 2017-02-28 a 18 15 31" src="https://cloud.githubusercontent.com/assets/951776/23416178/2345ec28-fde2-11e6-8085-b5807af88e84.png">

* File `boards.txt`under folder `~/Library/Energia15/packages/energia/hardware/msp430/1.0.2/boards.txt`

* File `boards.txt`folder
`/Applications/IDE/Energia.app/Contents/Java/hardware/energia/msp430/boards.txt` folder

**Comment by barawn** [comment]
I was asking for the package_index.json file so that it can be used as a model for building board manager packages. Since I don't know what the tools are called (in Board Manager-terms) that are installed, I can't make one of my own.

I did find it, though, buried in a temp directory (on Windows at least), but it would probably be a good idea to expose that package index somewhere where people can see it.

**Comment by rei-vilo** [comment]
Energia uses the same structure as Arduino, so all the Arduino documentation is relevant. 

See for example Boards Manager JSON index file format specification at
https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.6.x-package_index.json-format-specification

**Comment by barawn** [comment]
Right, but without that JSON file, you don't know what tools are already included in Energia, or where they're stored from. In the JSON on the temp directory, for instance, which I have no idea where it came from, it specifies the toolsDependencies as  "name":"msp430-gcc", "version":"4.6.3", "name":"dslite", "version":"6.2.1.1594", etc. So when I create one for my custom boards, I can use exactly those toolsDependencies so they're automatically satisfied by what's already installed.

**Comment by rei-vilo** [comment]
It is a practice to release self-contained packages, as Arduino does for the AVR package, stored along other packages instead of within the IDE.

**Comment by robertinant** [comment]
This is the repo for package_index.json https://github.com/robertinant/energia-package-index
The json file is downloaded by the IDE from http://energia.nu/packages/package_index.json. You can specify your own custom board packages index in the IDE's preferences. You will need to name it something other than package_index.json e.g. my_package_index.json.

**Comment by barawn** [comment]
Fantastic! Thanks, I didn't see that repository before.
