### ISSUE TITLE
macOS: MSP430F5529 Debug Interface Version

### ISSUE THREAD

**Issue by rei-vilo** [energia/msp430-lg-core#37]
On macOS, 

* Energia 1.6.1E0018 with `msp430-lg-core 1.0.1` boards package, and 
* CCS Cloud 

no longer share the same release of the debug interface for the **MSP430F5529**.

<img width="422" alt="capture 2017-03-24 a 12 41 13" src="https://cloud.githubusercontent.com/assets/951776/24292920/9c6a5048-108f-11e7-8a36-074f23a6de7d.png">

<img width="800" alt="capture 2017-03-24 a 12 43 32" src="https://cloud.githubusercontent.com/assets/951776/24292941/ae48eac2-108f-11e7-89a6-f8fc5aaede22.png">

I haven't tested on Windows or Linux.

**Comment by robertinant** [comment]
I am working on getting them back in sync.

**Comment by robertinant** [comment]
An updated msp430 package will be released later this week which get's them back in sync. I'll do my best to keep them in sync.
