### ISSUE TITLE
Make `pack_somnium_gcc.sh` OS-aware

### ISSUE THREAD

**Issue by rei-vilo** [energia/msp430-lg-core#38]
The `pack_somnium_gcc.sh` script is not OS-aware and thus proceeds with the download of the `msp430-gcc-6.2.1.16` four times (Linux 32, Linux 64, macOS, Windows).

Making it OS-aware would save time, space and bandwidth!

**Comment by StefanSch** [comment]
Target of the script is to make packages for all OS so that this are available for release. This should typically happen for all OS.
