### ISSUE TITLE
RAM for MSP430FR2433?

### ISSUE THREAD

**Issue by rei-vilo** [energia/msp430-lg-core#48]
https://github.com/energia/msp430-lg-core/blob/ea1295632420bd21ecd3fd8dc9fb6b462ee3cbf3/boards.txt#L42

Doesn't the MSP430FR2433 feature 4 KB of RAM?

```
 MSP-EXP430FR2433LP.upload.maximum_data_size=4096 
```

+ Boards package MSP430 1.0.3
+ Energia 1.8.5E19.

**Comment by robertinant** [comment]
Corrected with 1390d6768f2e044329281253f18ad7d743524ef3
