### ISSUE TITLE
MSP430FR4133 — Issue with I²C  

### ISSUE THREAD

**Issue by rei-vilo** [energia/msp430-lg-core#55]
The MSP430FR4133 uses software I²C on pins 9 and 10 for compatibility. However, only SCL signal seems to be generated.

The same sketch with the same [INA226 BoosterPack](https://e2e.ti.com/support/wireless_connectivity/simplelink_wifi_cc31xx_cc32xx/f/968/p/650530/2389881) works fine on the MSP430FR6989 LaunchPad. According to the [schematics](https://e2e.ti.com/cfs-file/__key/communityserver-discussions-components-files/968/11_2D00_-WCS033A_2800_Boosterpack_29005F00_Sch.PDF), SCL and SDA have 10 kΩ pull-up resistors.

I'm using MSP430 boards package release 1.0.3.

![capture 2018-01-31 a 09 42 16](https://user-images.githubusercontent.com/951776/35613144-7e1a4148-066b-11e8-8d75-46c3ef48a859.png)

```
#include "Wire.h"

#define INA226_I2C_ADDRESS 0x40
#define INA226_REGISTER_MANUFACTURER_ID 0xfe
#define INA226_REGISTER_DIE_ID          0xff


int16_t read16(uint8_t address)
{
  int16_t value = 0;

  Wire.beginTransmission(INA226_I2C_ADDRESS);
  Wire.write(address);
  Wire.endTransmission();

  Wire.requestFrom(INA226_I2C_ADDRESS, 2);
  while (Wire.available() < 2)
  {
    Serial.print(".");
  }

  value = Wire.read();
  value <<= 8;
  value += Wire.read();

  return value;
}


void setup() {
  Wire.begin();
  Serial.begin(9600);
}

void loop() {
  Serial.print("5449 ? ");
  Serial.println(read16(INA226_REGISTER_MANUFACTURER_ID), HEX); // 5449
  Serial.print("2260 ? ");
  Serial.println(read16(INA226_REGISTER_DIE_ID), HEX); // 2260
  delay(100);

}
```

**Comment by StefanSch** [comment]
Can you please check if both (SDA and SCL) have pull up resistor on the BoosterPack.

**Comment by rei-vilo** [comment]
Yes, the [schematics](https://e2e.ti.com/cfs-file/__key/communityserver-discussions-components-files/968/11_2D00_-WCS033A_2800_Boosterpack_29005F00_Sch.PDF) shows both SCL and SDA have 10 kΩ pull-up resistors.

![11- wcs033a boosterpack _sch](https://user-images.githubusercontent.com/951776/35625767-c5c39dd2-0693-11e8-94d5-11c4bf5a9efa.jpg)

**Comment by rei-vilo** [comment]
Same happens with the Sensors BoosterPack and the `WeatherSensors_Demo` example.

> TMP007_internalTemperature 0.00°C
> TMP007_externalTemperature 0.00°C
> OPT3001_light             0.00lux
> BME280_pressure           0.00hPa
> BME280_temperature        0.00°C
> BME280_humidity           0.00%

![boostxl-sensors_schematic](https://user-images.githubusercontent.com/951776/35626399-e85480d0-0695-11e8-992b-59eae0254c2a.jpg)

**Comment by StefanSch** [comment]
The sensor BoosterPack has the I2C on pins 14 and 15 while the default for Energia is 9 and 10.

So you have to add
Wire.setModule(0);

**Comment by StefanSch** [comment]
Hope this helps - if not let me know and i will debug into it.

**Comment by rei-vilo** [comment]
Here are the results of my tests


- Test MSP430FR2433 I²C with INA226

Wire.setModule | Pins | Result
---- | ---- | ----
Wire.setModule(0); | 14 + 15 | 5449 =? 5449
Wire.setModule(1); | 14 + 15 | 5449 =? 0
Wire.setModule(0); | 9 + 10 | 5449 =? ................ERROR
Wire.setModule(1); | 9 + 10 | 5449 =? 0

- Test MSP430FR6989 I²C with INA226

Wire.setModule | Pins | Result
---- | ---- | ----
Wire.setModule(1); | 9 + 10 | 5449 =? 5449
No Wire.setModule = default = 1 | 9 + 10 | 5449 =? 5449

- Code

```
#include "Wire.h"

#define INA226_I2C_ADDRESS 0x40
#define INA226_REGISTER_MANUFACTURER_ID 0xfe

void setup()
{
    Serial.begin(9600);
    Wire.setModule(0);
    Wire.begin();
    delay(100);

    Serial.println("Test MSP430FR2433 I2C with INA226");
    Serial.println("Wire.setModule(0);");
    Serial.println("----");
    Serial.print("5449 =? ");

    Wire.beginTransmission(INA226_I2C_ADDRESS);
    Wire.write(INA226_REGISTER_MANUFACTURER_ID);
    Wire.endTransmission();

    uint16_t count = 16;
    uint16_t value = 0;
    Wire.requestFrom(INA226_I2C_ADDRESS, 2);
    while ((Wire.available() < 2) and (count > 0))
    {
        delay(100);
        Serial.print(".");
        count--;
    }

    if (count > 0) {
        value = Wire.read();
        value <<= 8;
        value += Wire.read();
        Serial.println(value, HEX);
    } else {
        Serial.println("ERROR");
    }
    Serial.println("====");

}

void loop()
{

}
```

**Comment by StefanSch** [comment]
A little bit confused now - which launchpad shows the error: 
MSP430FR4311 (title say 4133 but that does not exist)
MSP430FR2433 (as in the last comment)?

**Comment by rei-vilo** [comment]
Sorry, the LaunchPad with issues is the MSP430FR4133. 
The reference LaunchPad that works is the MSP430FR6989.

**Comment by StefanSch** [comment]
fixed in branch issue_55
