### ISSUE TITLE
Hardware I²C No Longer Works on MSP432G2553 and MSP430FR5994

### ISSUE THREAD

**Issue by rei-vilo** [energia/msp430-lg-core#62]
Targeting the MSP430G2553 and using the BME280 sensor.

- Emulated I²C on pins 9 + 10 works with Energia 17.
![capture__2018-05-18_a_23 28 52-crunch](https://user-images.githubusercontent.com/951776/40259179-7e276984-5af5-11e8-9cda-be00309810ff.png)

- Hardware I²C on pins 14 + 15 does not work with Energia 17.
![capture__2018-05-18_a_23 28 59-crunch](https://user-images.githubusercontent.com/951776/40259237-a97e2aaa-5af5-11e8-95f2-efb396bdc220.png)

- Hardware I²C on pins 14 + 15 works with Energia 12.
![capture__2018-05-18_a_23 28 55-crunch](https://user-images.githubusercontent.com/951776/40259186-85a4a3a2-5af5-11e8-812d-298fb41b6a41.png)

Please refer to https://forum.43oh.com/topic/13153-cant-get-bme280-to-work-with-msp430g2554/ for more details.

**Comment by rei-vilo** [comment]
Same issue on the MSP430FR5994.

**Comment by StefanSch** [comment]
There is a fix already commited into the master branch but not in the release.
Using this i do not see an issue on FR5994 I2C on pin 14/15 (did not test 9/10)

**Comment by rei-vilo** [comment]
No, it is just that legacy I²C (hardware, master+ slave) no longer worked on pins 14 + 15.

**Comment by StefanSch** [comment]
All device now have I2C default on 9/10. But most of them can selected another module (SetModule) and then also use the legacy I2C on 14/15.
If 9/10 do not have hardware I2C pins mapped there it will use the SW functions.
