### ISSUE TITLE
MSP430FR2355 with 4 KB RAM 

### ISSUE THREAD

**Issue by rei-vilo** [energia/msp430-lg-core#81]
Isn't SRAM 4 KB as per http://www.ti.com/product/MSP430FR2355?

https://github.com/energia/msp430-lg-core/blob/a103a47adbe8f676dbfb51ddb85f7e7e9f5ed17c/boards.txt#L194

**Comment by StefanSch** [comment]
you are right - unfortunately this did not get into the last commit for the FR2355

**Comment by StefanSch** [comment]
fixed with 
https://github.com/energia/msp430-lg-core/pull/82
