### ISSUE TITLE
generated define for board not valid

### ISSUE THREAD

**Issue by StefanSch** [energia/msp430-lg-core#9]
The energia framework generates define which identifies the selected board.
e.g.
-DENERGIA_MSP-EXP430F5529LP 
this is an invalid define as defines does not allow the '-' character.
the compiler also reports an warning which i assume corresponds to that.
<command-line>:0:12: warning: missing whitespace after the macro name [enabled by default]

This might happen for other boards as well - so a replace of '-' with '_' might be a good option when generating the defines.

**Comment by robertinant** [comment]
fixed with 73d5cbc520a0c1ca28edcceedecd83cc982f5f14
