### ISSUE TITLE
MSP430FR5994 GPIO pin 18 no longer works as an `OUPUT`

### ISSUE THREAD

**Issue by rei-vilo** [energia/msp430-lg-core#90]
The fix for #83 has created a new issue. On the MSP430FR5994 LaunchPad, GPIO pin 18 no longer works as an `OUPUT`. I haven't tested the other pins yet.

<img width="1026" alt="capture 2019-01-08 a 22 19 34" src="https://user-images.githubusercontent.com/951776/50859588-0ca8fe00-1394-11e9-9c5f-7393ae09a9c1.png">

With the release previous to the fix for #83, 

<img width="1026" alt="capture 2019-01-08 a 22 19 02" src="https://user-images.githubusercontent.com/951776/50859583-0a46a400-1394-11e9-94e2-df98866c9599.png">

The minimalistic code is

```
const uint8_t EPD_FLASH_CS = 18;

void setup() 
{    
    pinMode(EPD_FLASH_CS, OUTPUT);
    digitalWrite(EPD_FLASH_CS, HIGH);    
}

void loop() 
{
    digitalWrite(EPD_FLASH_CS, LOW);
    delay(10);
    digitalWrite(EPD_FLASH_CS, HIGH);
    delay(10);
}
```

**Comment by StefanSch** [comment]
fixed in issue 83 branch
