### ISSUE TITLE
Updated I²C library — Feed-back + suggestion

### ISSUE THREAD

**Issue by rei-vilo** [energia/msp430-lg-core#97]
I've tested the updated I²C library on an MSP430FR4133 connected to an INA226 sensor. Everything when fine.

I haven't tested the library as I²C slave yet.

A nice addition would be to allow to choose between the different speeds or modes (links to www.i2c-bus.org website).

+ [Standard mode](https://www.i2c-bus.org/standard-mode/) at 100 kb/s (default)
+ [Fast mode](https://www.i2c-bus.org/fastmode/) at 400 kb/s
+ [Fast mode+](https://www.i2c-bus.org/fast-mode-plus/) at 1 Mb/s, when available

**Comment by StefanSch** [comment]
Hi,
just pushed a version to the wire_update branch.
If you would like to give it a try.
Note: it uses the function prototypes from Arduino with e.g.
Wire.setClock(400000); // set 400kb/s

~ Stefan

**Comment by rei-vilo** [comment]
Thanks, I'll give a try and let you know!

**Comment by StefanSch** [comment]
added in wire_update branchand merged.
Note: MSP430 only supports speed up to 400k
